[package]
name = "sc-swap-esdt-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.sc-swap-esdt]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.30.0"
